//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessingTests.DocService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocService.IDocumentService")]
    public interface IDocumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GenerateDocument", ReplyAction="http://tempuri.org/IDocumentService/GenerateDocumentResponse")]
        System.IO.Stream GenerateDocument(string documentText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GenerateDocument", ReplyAction="http://tempuri.org/IDocumentService/GenerateDocumentResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GenerateDocumentAsync(string documentText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GetLog", ReplyAction="http://tempuri.org/IDocumentService/GetLogResponse")]
        int GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GetLog", ReplyAction="http://tempuri.org/IDocumentService/GetLogResponse")]
        System.Threading.Tasks.Task<int> GetLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : DocumentProcessingTests.DocService.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<DocumentProcessingTests.DocService.IDocumentService>, DocumentProcessingTests.DocService.IDocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GenerateDocument(string documentText) {
            return base.Channel.GenerateDocument(documentText);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GenerateDocumentAsync(string documentText) {
            return base.Channel.GenerateDocumentAsync(documentText);
        }
        
        public int GetLog() {
            return base.Channel.GetLog();
        }
        
        public System.Threading.Tasks.Task<int> GetLogAsync() {
            return base.Channel.GetLogAsync();
        }
    }
}
